accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup" ),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("ice_cream/", include("ice_cream.urls", namespace="ice_cream")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),
]

ice_cream/urls.py
from django.urls import path

from . import views

app_name = "ice_cream"

urlpatterns = [
    path("<int:pk>/", views.DeleteIceCream.as_view(), name="delete"),
    path("new/", views.CreateIceCream.as_view(), name="create"),
    path("results/<int:pk>", views.ResultsView.as_view(), name="results"),
    path("vote/<int:pk>", views.vote, name="vote"),
    path("<str:selection>/", views.index, name="selection"),
    path("", views.index, name="index")
]

accounts/models.py
from django.db import models

# Create your models here.

ice_cream/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

import datetime

class IceCream(models.Model):

    CHOCOLATE = 'CHOCOLATE'
    VANILLA = 'VANILLA'

    BASE_CHOICES = [
        (CHOCOLATE, 'Chocolate'),
        (VANILLA, 'Vanilla'),
    ]

    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    SEASONAL = "SEASONAL"

    AVAILABLE_CHOICES =[
        (DAILY, "Daily"),
        (WEEKLY, "Weekly"),
        (SEASONAL, "Seasonal"),
    ]

    flavor = models.CharField(max_length=255)
    base = models.CharField(max_length=255, choices=BASE_CHOICES, default=VANILLA)


    available = models.CharField(max_length=255, choices=AVAILABLE_CHOICES, default=WEEKLY)




    featured = models.BooleanField(default=False)
    date_churned = models.DateField("Date Churned", default=datetime.date.today)


    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.flavor

    def get_absolute_url(self):
        return reverse("ice_cream:index")

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.

class SignupView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "signup.html"

ice_cream/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import IceCream
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy
from django.views import generic

# Create your views here.
def index(request, selection=None):

    if selection == "home":
        ice_cream_list = IceCream.objects.all()
    elif selection == 'featured':
        ice_cream_list = IceCream.objects.filter(featured=True)
    elif selection != None:
        ice_cream_list = IceCream.objects.filter(available=selection.upper())
    else:
        ice_cream_list = IceCream.objects.all()

    context = {
        "ice_cream_list": ice_cream_list
    }

    return render(request, "ice_cream/index.html", context)


class ResultsView(generic.DetailView):
    model = IceCream
    template_name ="ice_cream/results.html"

def vote(request, pk):

    ice_cream = get_object_or_404(IceCream, pk=pk)
    # e.g. {'flavor': 'vanilla', 'available': 'weekly', 'featured': True, likes: 0}

    ice_cream.likes += 1
    ice_cream.save()

    return HttpResponseRedirect(reverse('ice_cream:results', args=(ice_cream.id,)))


class CreateIceCream(generic.CreateView):

    model = IceCream
    # fields = '__all__'
    fields = ["flavor","base","available","featured","date_churned",]
    template_name = "ice_cream/create.html"

class DeleteIceCream(generic.DeleteView):
    model = IceCream
    success_url = reverse_lazy("ice_cream:index")

def is_superuser_check(user):
    return user.is_superuser

accounts/templates/signup.html
<h2>Sign up </h2>
<form>
    {% csrf_token %}
    {{form.as_p}}
    <button>Login</button>

</form>

ice_cream/templates/ice_cream/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    </head>
    <body>
        <div class="container">
        <header class="d-flex row justify-content-center mb-5">
            <h1 class="d-flex col-12 justify-content-center">Zay's IceCream Shop</h1>
            <nav class="d-flex col-12 justify-content-around">
                <a href="{% url 'ice_cream:selection' 'home' %}"><span>Home</span></a>
                <a href="{% url 'ice_cream:selection' 'featured' %}"><span>Featured</span></a>
                <a href="{% url 'ice_cream:selection' 'daily'%}"><span>Daily</span></a>
                <a href="{% url 'ice_cream:selection' 'weekly'%}"><span>Weekly</span></a>
                <a href="{% url 'ice_cream:selection' 'seasonal'%}"><span>Seasonal</span></a>
                <a href="{% url 'ice_cream:create' %}"><span>New Flavor</span></a>
                <a href="{% url 'login' %}">Login</a>
                <a href="{% url 'logout' %}"> Logout</a>
            </nav>
        </header>
        {% block content %}
        {% endblock %}
        </div>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>

</html>

ice_cream/templates/ice_cream/create.html
{% extends "ice_cream/base.html" %}
{% block content %}
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button>Submit</button>
</form>
{% endblock %}

ice_cream/templates/ice_cream/index.html
{% extends "ice_cream/base.html" %}
{% block content %}

{% if ice_cream_list %}

    <ul class="row">
        {% for ice_cream in ice_cream_list %}
        <li class="d-flex col-4 align-items-center mb-4">
            {{ ice_cream.flavor }}

            <form class="mb-0" action="{% url 'ice_cream:vote' ice_cream.id %}" method="post" >
                {% csrf_token %}

                    <input type="button" name="ice_cream" id="ice_cream.id" value="likes:{{ice_cream.id}}" hidden>
                    <label class="ml-1 mb-0" for="ice_cream.id">Likes:{{ice_cream.likes}}</label>
                    <button>Like</button>
            </form>

            <form class="mb-0" action="{% url 'ice_cream:delete' ice_cream.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="delete" />
            </form>
        </li>
        {% endfor %}
    </ul>

{% else %}

<p>
    you messed somethin up
    </p>

{% endif %}

{% endblock %}

ice_cream/templates/ice_cream/results.html
{% extends "ice_cream/base.html" %}
{% block content %}

<h2>Thank you for you vote!</h2>



<p>{{object.flavor}} now has a like count of : <span>{{object.likes}}</span></p>




{% endblock %}